---
title: "Passwords"
output: html_document
---

```{r libraries}
library(tidyverse)
library(paletteer)
library(janitor)
```

```{r data}
passwords <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-14/passwords.csv')
```

```{r drop na}
passwords <- passwords %>% 
  drop_na()
```

```{r prepare}
x <- c(seq(1,10), seq(2,11), seq(3,11), seq(4,10))

y <- c(rep(4, times = 10), rep(3, times = 10), rep(2, times = 9), rep(1, times = 7))

order <- c("1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "q", "w", "e", "r", "t", "y", "u", "i", "o", "p", "a", "s", "d", "f", "g", "h", "j", "k", "l", "z", "x", "c", "v", "b", "n", "m")

order2 <- c(seq(1,36))

order <- enframe(order) %>% 
  select(value) %>% 
  add_column(order = order2)

freq <- passwords %>% 
  pull(password) %>% 
  strsplit(split = "") %>% 
  unlist() %>% 
  table() %>%
  as_tibble() %>% 
  clean_names() %>% 
  rename("character" = x) %>% 
  left_join(order, by = c("character" = "value")) %>% 
  arrange(order) %>% 
  add_column(x = x, y = y)
```

```{r plot}
ggplot(freq,aes(x, y))+
  geom_tile(aes(fill = n))+
  geom_text(aes(label = character), color = "black")+
  coord_equal()+
  theme_void()+
  theme(
    legend.position = "bottom", 
    text = element_text(family = "Roboto Slab"),
    plot.title = element_text(hjust = 0, face = "bold"),
    plot.subtitle = element_text(hjust = 0),
    plot.background = element_rect(fill = "#f5deb3"),
    panel.grid.major = element_line(colour = "transparent"),
    plot.margin = unit(c(1, 1, 1, 1), 'cm')
    )+
  scale_fill_paletteer_c("ggthemes::Blue")+
  labs(title = "Which keys are most commonly used for passwords?", subtitle = "In the 500 most popular passwords",fill = "", caption = "Data: http://bit.ly/KIB_PopularPasswords \n@Rzeugnisse • #TidyTuesday")

ggsave("Tidytuesday_week_3.png", width = 11.5, height = 6, dpi = 300)
```

```{r remix geokaramanis}
ggplot(freq,aes(x, y))+
  geom_tile(fill = "black")+
  geom_text(aes(label = character, alpha = n), color = "green3")+
  theme_void()+
  theme(
    legend.position = "none", 
    text = element_text(family = "Press Start 2P", color = "green3"),
    plot.title = element_text(hjust = 0, face = "bold", size = 8),
    plot.subtitle = element_text(hjust = 0, size = 4),
    plot.caption = element_text(size = 4),
    plot.background = element_rect(fill = "#000000"),
    panel.grid.major = element_line(colour = "transparent"),
    plot.margin = unit(c(1, 1, 1, 1), 'cm'),
    legend.text = element_text(size = 4)
    )+
  scale_alpha(guide = 'none')+
  # scale_color_paletteer_c("grDevices::rainbow")+
  labs(title = "Which keys are most commonly used for passwords?", subtitle = "In the 500 most popular passwords",alpha = "", caption = "Data: http://bit.ly/KIB_PopularPasswords \noriginal @geokaramanis\n@Rzeugnisse • #TidyTuesday")
  
ggsave("Tidytuesday_week_3_remix.png", width = 10, height = 6, dpi = 300)
```

```{r remix RGB geokaramanis}
ggplot(freq,aes(x, y))+
  geom_tile(fill = "black")+
  geom_text(aes(label = character, alpha = n, color = n))+
  theme_void()+
  theme(
    legend.position = "none", 
    text = element_text(family = "Press Start 2P", color = "green3"),
    plot.title = element_text(hjust = 0, face = "bold", size = 8),
    plot.subtitle = element_text(hjust = 0, size = 4),
    plot.caption = element_text(size = 4),
    plot.background = element_rect(fill = "#000000"),
    panel.grid.major = element_line(colour = "transparent"),
    plot.margin = unit(c(1, 1, 1, 1), 'cm'),
    legend.text = element_text(size = 4)
    )+
  scale_alpha(guide = 'none')+
  scale_color_paletteer_c("grDevices::rainbow")+
  labs(title = "Which keys are most commonly used for passwords?", subtitle = "In the 500 most popular passwords",alpha = "", caption = "Data: http://bit.ly/KIB_PopularPasswords \noriginal @geokaramanis\n@Rzeugnisse • #TidyTuesday")

ggsave("Tidytuesday_week_3_remix_rgb.png", width = 10, height = 6, dpi = 300)
```

```{r rect}
x1 <- c(seq(1,10), seq(1.5,10.5), seq(2,10), seq(2.5,8.5))

y1 <- c(rep(4, times = 10), rep(3, times = 10), rep(2, times = 9), rep(1, times = 7))

x2 <- x1+1

y2 <- y1+1

order <- c("1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "q", "w", "e", "r", "t", "y", "u", "i", "o", "p", "a", "s", "d", "f", "g", "h", "j", "k", "l", "z", "x", "c", "v", "b", "n", "m")

order2 <- c(seq(1,36))

order <- enframe(order) %>% 
  select(value) %>% 
  add_column(order = order2)

freq <- passwords %>% 
  pull(password) %>% 
  strsplit(split = "") %>% 
  unlist() %>% 
  table() %>%
  as_tibble() %>% 
  clean_names() %>% 
  rename("character" = x) %>% 
  left_join(order, by = c("character" = "value")) %>% 
  arrange(order) %>% 
  add_column(x1 = x1, y1 = y1, x2 = x2, y2 = y2)
```

```{r rect plot}
ggplot(freq)+
  geom_rect(aes(xmin = x1, xmax = x2, ymin = y1, ymax = y2, fill = n), color = "#f5deb3", size = 2)+
  geom_text(aes(x = x1 + (x2 - x1) / 2, y = y1 + (y2-y1) / 2, label = character), color = "black")+
  coord_equal()+
  theme_void()+
  theme(
    legend.position = "bottom", 
    text = element_text(family = "Roboto Slab"),
    plot.title = element_text(hjust = 0, face = "bold"),
    plot.subtitle = element_text(hjust = 0),
    plot.background = element_rect(fill = "#f5deb3"),
    panel.grid.major = element_line(colour = "transparent"),
    plot.margin = unit(c(1, 1, 1, 1), 'cm')
    )+
  scale_fill_paletteer_c("ggthemes::Blue")+
  labs(title = "Which keys are most commonly used for passwords?", subtitle = "In the 500 most popular passwords",fill = "", caption = "Data: http://bit.ly/KIB_PopularPasswords \n@Rzeugnisse • #TidyTuesday")

ggsave("Tidytuesday_week_3_rect.png", width = 11.05, height = 6, dpi = 300)
```

```{r rect plot rgb}
ggplot(freq)+
  geom_rect(aes(xmin = x1, xmax = x2, ymin = y1, ymax = y2), fill = "black")+
  geom_text(aes(x = x1 + (x2 - x1) / 2, y = y1 + (y2-y1) / 2, label = character, alpha = n, color = n))+
  theme_void()+
  theme(
    legend.position = "none", 
    text = element_text(family = "Press Start 2P", color = "green3"),
    plot.title = element_text(hjust = 0, face = "bold", size = 8),
    plot.subtitle = element_text(hjust = 0, size = 4),
    plot.caption = element_text(size = 4),
    plot.background = element_rect(fill = "#000000"),
    panel.grid.major = element_line(colour = "transparent"),
    plot.margin = unit(c(1, 1, 1, 1), 'cm'),
    legend.text = element_text(size = 4)
    )+
  scale_alpha(guide = 'none')+
  scale_color_paletteer_c("grDevices::rainbow")+
  labs(title = "Which keys are most commonly used for passwords?", subtitle = "In the 500 most popular passwords",alpha = "", caption = "Data: http://bit.ly/KIB_PopularPasswords \noriginal @geokaramanis\n@Rzeugnisse • #TidyTuesday")
```

```{r Apple Keyboard}
ggplot(freq)+
  geom_rect(aes(xmin = x1, xmax = x2, ymin = y1, ymax = y2), fill = "black", color = "#c0c5ce")+
  geom_text(aes(x = x1 + (x2 - x1) / 2, y = y1 + (y2-y1) / 2, label = character, alpha = n, color = n))+
  coord_equal()+
  theme_void()+
  theme(
    legend.position = "none", 
    text = element_text(family = "Helvetica", color = "green3"),
    plot.title = element_text(hjust = 0, face = "bold", size = 8),
    plot.subtitle = element_text(hjust = 0, size = 4),
    plot.caption = element_text(size = 4),
    plot.background = element_rect(fill = "#c0c5ce"),
    panel.grid.major = element_line(colour = "transparent"),
    plot.margin = unit(c(1, 1, 1, 1), 'cm'),
    legend.text = element_text(size = 4)
    )+
  scale_alpha(guide = 'none')+
  scale_color_paletteer_c("grDevices::rainbow")+
  labs(title = "Which keys are most commonly used for passwords?", subtitle = "In the 500 most popular passwords",alpha = "", caption = "Data: http://bit.ly/KIB_PopularPasswords \noriginal @geokaramanis\n@Rzeugnisse • #TidyTuesday")
```

